name: basketball_drills_workout
description: A Flutter app for basketball drill workouts.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"  # Make sure this file exists

flutter:
  uses-material-design: true

  assets:
    - assets/icon/icon.png
    - assets/images/
